### ISSUE TITLE
githubcontributors-block-macro test failing in Win7

### ISSUE THREAD

**Issue by abelsromero** [robertpanzer/asciidoctorj-extensions-lab#1]
I get some Ruby error when running the test on Windows 7 with Java 1.7 (64x - build 1.7.0-b147).
- First, I installed asciidoctorj-1-6.0 from the branch (https://github.com/asciidoctor/asciidoctorj/tree/asciidoctorj-1.6.0) using `gradlew install`
- then, I ran `gradlew test` from this projects' root but it fails with message below.

Any idea?

```
Expected no exception to be thrown, but got 'org.asciidoctor.internal.AsciidoctorCoreException'
    at spock.lang.Specification.noExceptionThrown(Specification.java:118)
    at org.asciidoctor.extensionslab.githubcontributors.GithubContributorsSpec.should create table of contributors(GithubContributorsSpec.groovy:20)
Caused by: org.asciidoctor.internal.AsciidoctorCoreException: org.jruby.exceptions.RaiseException: (TypeError) exception class/object expected
    at org.asciidoctor.internal.JRubyAsciidoctor.renderFile(JRubyAsciidoctor.java:314)
    at org.asciidoctor.internal.JRubyAsciidoctor.renderFile(JRubyAsciidoctor.java:427)
    at org.asciidoctor.internal.JRubyAsciidoctor.convertFile(JRubyAsciidoctor.java:528)
    at org.asciidoctor.extensionslab.githubcontributors.GithubContributorsSpec.should create table of contributors(GithubContributorsSpec.groovy:17)
Caused by: org.jruby.exceptions.RaiseException: (TypeError) exception class/object expected
    at RUBY.load(C:/Users/asalgadr/.m2/repository/org/asciidoctor/asciidoctorj/1.6.0-SNAPSHOT/asciidoctorj-1.6.0-SNAPSHOT.jar!/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1362)
    at RUBY.convert(C:/Users/asalgadr/.m2/repository/org/asciidoctor/asciidoctorj/1.6.0-SNAPSHOT/asciidoctorj-1.6.0-SNAPSHOT.jar!/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1458)
    at RUBY.convert_file(C:/Users/asalgadr/.m2/repository/org/asciidoctor/asciidoctorj/1.6.0-SNAPSHOT/asciidoctorj-1.6.0-SNAPSHOT.jar!/gems/asciidoctor-1.5.2/lib/asciidoctor.rb:1562)
    at RUBY.convertFile(<script>:68)
    at org.jruby.gen.InterfaceImpl2035734322.convertFile(org/jruby/gen/InterfaceImpl2035734322.gen:13)
    ... 1 more
```

_I tried running the test in UNSAFE just in case it was a network issue, but it didn't help_

**Comment by robertpanzer** [comment]
Hi Abel,

did you build with the latest AsciidoctorJ?
I merged required changes just about an hour ago.

**Comment by abelsromero** [comment]
Fixed with the last changes :+1: You're awesome!

Btw, maybe you should consider adding the unsafe mode. It embeds the CSS and creates a render just a little bit nicer.

```
log.info asciidoctor.convertFile(new File('src/test/resources/asciidoctorj.adoc'), OptionsBuilder.options().safe(SafeMode.UNSAFE).headerFooter(true))
```

**Comment by robertpanzer** [comment]
Abel, thank you for the tip!
I was already wondering why the html did not contain the css in contrast to when rendering with the CLI, now I know! :)
Will do that tomorrow. 

BTW: These samples should also showcase the API. If you feel that something is not that clean yet or could be ameliorated it would be great to get some feedback.

**Comment by robertpanzer** [comment]
Just pushed activating safe mode. Looks much better now! Thank you!
